name: Claude Summarize
description: AI-powered build failure analysis using Claude via Buildkite
author: https://github.com/mcncl
requirements:
  - bash
  - curl
  - jq
configuration:
  properties:
    custom_prompt:
      type: string
      description: Additional context to include in the analysis
    api_token:
      type: string
      description: Buildkite API token with read_builds scope (can also use BUILDKITE_API_TOKEN env var)
  required: []
  additionalProperties: false
