name: Claude Summarize
description: AI hacking
author: https://github.com/jfhinchcliffe
requirements:
  - bash
  - curl
configuration:
  properties:
    prompt:
      type: string
      description: Prompt to send to AI
  required: [prompt]
  additionalProperties: false
