name: Claude Summarize
description: AI-powered build failure analysis using Claude via Buildkite
author: https://github.com/mcncl
requirements:
  - bash
  - curl
  - jq
configuration:
  properties:
    api_key:
      type: string
      description: Buildkite API token with read_builds scope
    custom_prompt:
      type: string
      description: Additional context for the AI analysis
  required: []
  additionalProperties: false
