steps:
  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files:
            - hooks/**
            - lib/**
            - tests/**

  - label: ":test_tube: Tests"
    plugins:
      - docker-compose#v5.10.0:
          run: tests

  - label: ":book: Lint"
    plugins:
      - plugin-linter#v2.1.0:
          id: claude-code
